In [3]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
1 / arr
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [5]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [6]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [8]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [9]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [11]:
arr2d[0][2]
arr2d[0, 2]

np.int64(3)

In [12]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
arr3d[1, 0]

array([7, 8, 9])

In [16]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

In [17]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [18]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [20]:
lower_dim_slice = arr2d[1, :2]

In [21]:
lower_dim_slice.shape

(2,)

In [22]:
arr2d[:2, 2]

array([3, 6])

In [23]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [24]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])